# Generated by Django 4.1 on 2022-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Trektrip', models.CharField(blank=True, max_length=100)),
                ('suggestions', models.TextField(default='0', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('card_type', models.CharField(max_length=100)),
                ('mo_num', models.CharField(max_length=200)),
                ('acnum', models.IntegerField()),
                ('card_num', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('mo_num', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
