# Generated by Django 4.1 on 2022-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkersspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mo_num',
            field=models.IntegerField(max_length=100),
        ),
    ]
